import { GoogleGenAI } from '@google/genai';
import OpenAI from 'openai';
import { UTApi } from 'uploadthing/server';
import {
  EMOJI_GENERATION_PROMPT_VERSION,
  getEmojiGenerationCacheKey,
  getEmojiGenerationPrompt,
} from '@/lib/prompts/emoji-generation';

export type EmojiProvider = 'gemini' | 'gpt-image';

type GenerateEmojiImageOptions = {
  productName: string;
  description?: string;
  provider?: string;
};

type UploadEmojiImageOptions = {
  imageBuffer: Buffer;
  productName?: string;
  utapi?: UTApi;
};

function getProvider(value?: string): EmojiProvider {
  return value === 'gpt-image' ? 'gpt-image' : 'gemini';
}

function emojiFileName(productName?: string) {
  const slug = productName?.toLowerCase().trim().replace(/\s+/g, '-') || 'product';
  return `ai-emoji-${slug}-${Date.now()}.png`;
}

async function generateWithGemini({
  productName,
  description,
  apiKey,
}: {
  productName: string;
  description?: string;
  apiKey: string;
}) {
  const prompt = getEmojiGenerationPrompt(productName, description);
  const ai = new GoogleGenAI({ apiKey });
  const model = process.env.IMAGEN_MODEL || 'imagen-4.0-generate-001';

  const response = await ai.models.generateImages({
    model,
    prompt,
    config: {
      numberOfImages: 1,
      aspectRatio: '1:1',
    },
  });

  if (!response?.generatedImages?.length) {
    throw new Error(
      'No image generated by Imagen - content may have been blocked by safety filters'
    );
  }

  const imageBytes = response.generatedImages[0]?.image?.imageBytes;
  if (!imageBytes) {
    throw new Error('Missing image data in Imagen response');
  }

  return {
    imageBuffer: Buffer.from(imageBytes, 'base64'),
    model,
    prompt,
  };
}

async function generateWithOpenAI({
  productName,
  description,
  apiKey,
}: {
  productName: string;
  description?: string;
  apiKey: string;
}) {
  const prompt = getEmojiGenerationPrompt(productName, description);
  const model = 'gpt-image-1.5';
  const openai = new OpenAI({ apiKey });

  const result = await openai.images.generate({
    model,
    prompt,
  });

  const imageBase64 = result.data?.[0]?.b64_json;
  if (!imageBase64) {
    throw new Error('No image data from GPT Image');
  }

  return {
    imageBuffer: Buffer.from(imageBase64, 'base64'),
    model,
    prompt,
  };
}

export async function generateEmojiImage({
  productName,
  description,
  provider: providerInput = process.env.AI_PROVIDER,
}: GenerateEmojiImageOptions) {
  const provider = getProvider(providerInput);
  const cacheKey = getEmojiGenerationCacheKey(productName, description);

  if (provider === 'gpt-image') {
    const apiKey = process.env.OPENAI_API_KEY;
    if (!apiKey) {
      throw new Error('OpenAI API key not configured');
    }
    const generated = await generateWithOpenAI({ productName, description, apiKey });
    return {
      ...generated,
      provider,
      promptVersion: EMOJI_GENERATION_PROMPT_VERSION,
      cacheKey,
    };
  }

  const apiKey = process.env.GOOGLE_GENAI_API_KEY;
  if (!apiKey) {
    throw new Error('Google Generative AI API key not configured');
  }
  const generated = await generateWithGemini({ productName, description, apiKey });
  return {
    ...generated,
    provider,
    promptVersion: EMOJI_GENERATION_PROMPT_VERSION,
    cacheKey,
  };
}

export async function uploadEmojiImage({
  imageBuffer,
  productName,
  utapi = new UTApi(),
}: UploadEmojiImageOptions) {
  const fileName = emojiFileName(productName);
  const file = new File([new Uint8Array(imageBuffer)], fileName, { type: 'image/png' });
  const uploadResult = await utapi.uploadFiles(file);

  if (!uploadResult || uploadResult.error) {
    throw new Error('Failed to upload image to storage');
  }

  const imageUrl = uploadResult.data?.url;
  if (!imageUrl) {
    throw new Error('Upload succeeded but no URL returned');
  }

  return {
    imageUrl,
    fileName,
  };
}

export function base64ToImageBuffer(base64: string) {
  const base64Data = base64.replace(/^data:image\/\w+;base64,/, '');
  return Buffer.from(base64Data, 'base64');
}

export async function uploadEmojiBase64Image({
  base64,
  productName,
}: {
  base64: string;
  productName?: string;
}) {
  return uploadEmojiImage({
    imageBuffer: base64ToImageBuffer(base64),
    productName,
  });
}

export async function generateAndUploadEmojiAsset({
  productName,
  description,
  provider,
}: GenerateEmojiImageOptions) {
  const generated = await generateEmojiImage({ productName, description, provider });
  const uploaded = await uploadEmojiImage({
    imageBuffer: generated.imageBuffer,
    productName,
  });

  return {
    ...uploaded,
    provider: generated.provider,
    model: generated.model,
    promptVersion: generated.promptVersion,
    cacheKey: generated.cacheKey,
  };
}
