import { GoogleGenAI } from '@google/genai';
import type { GenerateContentResponse } from '@google/genai';
import OpenAI from 'openai';
import { getEmojiGenerationPrompt } from '@/lib/prompts/emoji-generation';

export const GOOGLE_IMAGE_MODEL_ENV = 'GOOGLE_IMAGE_MODEL';
export const OPENAI_IMAGE_MODEL_ENV = 'OPENAI_IMAGE_MODEL';
export const DEFAULT_OPENAI_IMAGE_MODEL = 'gpt-image-1.5';

const MAX_IMAGE_BYTES = 10 * 1024 * 1024;
const PNG_SIGNATURE = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);

// Model id grammar, not a catalogue of models: an id that matches is routed, it is not guaranteed
// that the model itself can generate images.
const IMAGEN_MODEL_ID_PATTERN = /^imagen-[a-z0-9]+(?:[.-][a-z0-9]+)*$/;
const GEMINI_IMAGE_MODEL_ID_PATTERN =
  /^gemini-[a-z0-9]+(?:[.-][a-z0-9]+)*-image(?:-[a-z0-9]+(?:[.-][a-z0-9]+)*)?$/;

// Values verified against the installed @google/genai FinishReason enum.
const BLOCKED_FINISH_REASONS = new Set([
  'SAFETY',
  'RECITATION',
  'BLOCKLIST',
  'PROHIBITED_CONTENT',
  'SPII',
  'IMAGE_SAFETY',
  'IMAGE_PROHIBITED_CONTENT',
  'IMAGE_RECITATION',
]);

type GenerateImageInput = {
  productName: string;
  description?: string;
  apiKey: string;
};

type GenerateImageWithModelInput = GenerateImageInput & { model: string };

type GeneratedImage = {
  imageBuffer: Buffer;
  model: string;
  prompt: string;
};

type GoogleImageAdapter = 'generateImages' | 'generateContent';

function readModelEnv(name: string): string | undefined {
  const raw = process.env[name];
  if (typeof raw !== 'string') {
    return undefined;
  }
  const trimmed = raw.trim();
  return trimmed.length > 0 ? trimmed : undefined;
}

function resolveGoogleImageAdapter(model: string): GoogleImageAdapter {
  if (IMAGEN_MODEL_ID_PATTERN.test(model)) {
    return 'generateImages';
  }
  if (GEMINI_IMAGE_MODEL_ID_PATTERN.test(model)) {
    return 'generateContent';
  }
  throw new Error(
    `Invalid ${GOOGLE_IMAGE_MODEL_ENV} value "${model}": expected an Imagen model id (${IMAGEN_MODEL_ID_PATTERN.source}) for generateImages or a Gemini image model id (${GEMINI_IMAGE_MODEL_ID_PATTERN.source}) for generateContent`
  );
}

async function generateWithLegacyGemini({
  productName,
  description,
  apiKey,
}: GenerateImageInput): Promise<GeneratedImage> {
  const prompt = getEmojiGenerationPrompt(productName, description);
  const ai = new GoogleGenAI({ apiKey });
  const model = process.env.IMAGEN_MODEL || 'imagen-4.0-generate-001';

  const response = await ai.models.generateImages({
    model,
    prompt,
    config: {
      numberOfImages: 1,
      aspectRatio: '1:1',
    },
  });

  if (!response?.generatedImages?.length) {
    throw new Error(
      'No image generated by Imagen - content may have been blocked by safety filters'
    );
  }

  const imageBytes = response.generatedImages[0]?.image?.imageBytes;
  if (!imageBytes) {
    throw new Error('Missing image data in Imagen response');
  }

  return {
    imageBuffer: Buffer.from(imageBytes, 'base64'),
    model,
    prompt,
  };
}

async function generateWithGoogleImages({
  productName,
  description,
  apiKey,
  model,
}: GenerateImageWithModelInput): Promise<GeneratedImage> {
  const prompt = getEmojiGenerationPrompt(productName, description);
  const ai = new GoogleGenAI({ apiKey });

  const response = await ai.models.generateImages({
    model,
    prompt,
    config: {
      numberOfImages: 1,
      aspectRatio: '1:1',
    },
  });

  if (!response?.generatedImages?.length) {
    throw new Error(
      'No image generated by Imagen - content may have been blocked by safety filters'
    );
  }

  const imageBytes = response.generatedImages[0]?.image?.imageBytes;
  if (!imageBytes) {
    throw new Error('Missing image data in Imagen response');
  }

  return {
    imageBuffer: Buffer.from(imageBytes, 'base64'),
    model,
    prompt,
  };
}

function classifyFinishReason(finishReason: string | undefined) {
  if (finishReason === undefined || finishReason === 'STOP') {
    return;
  }
  if (BLOCKED_FINISH_REASONS.has(finishReason)) {
    throw new Error(`Emoji image generation blocked (finishReason=${finishReason})`);
  }
  throw new Error(`Emoji image generation incomplete (finishReason=${finishReason})`);
}

function readBlockedPromptReason(response: GenerateContentResponse) {
  const blockReason = response?.promptFeedback?.blockReason;
  return blockReason ? String(blockReason) : 'none';
}

function readGenerateContentImage(response: GenerateContentResponse): Buffer {
  const candidates = response?.candidates;
  if (!candidates?.length) {
    throw new Error(
      `Emoji image generation blocked-prompt (blockReason=${readBlockedPromptReason(response)})`
    );
  }

  const candidate = candidates[0];
  classifyFinishReason(candidate?.finishReason as string | undefined);

  const parts = candidate?.content?.parts ?? [];
  const finalImageParts = parts.filter((part) => part?.inlineData && part.thought !== true);
  const firstImagePart = finalImageParts[0];
  if (!firstImagePart) {
    throw new Error('Emoji image generation no-image: response has no final image part');
  }

  const inlineData = firstImagePart.inlineData;
  if (inlineData?.mimeType !== 'image/png') {
    throw new Error('Emoji image generation unsupported-format: expected an image/png part');
  }

  const data = inlineData.data;
  if (!data) {
    throw new Error('Emoji image generation empty-image: response part carries no image data');
  }

  const imageBuffer = Buffer.from(data, 'base64');
  if (imageBuffer.length === 0) {
    throw new Error('Emoji image generation empty-image: image data decoded to zero bytes');
  }
  if (!imageBuffer.subarray(0, PNG_SIGNATURE.length).equals(PNG_SIGNATURE)) {
    throw new Error('Emoji image generation invalid-png: image data is not a PNG');
  }
  if (imageBuffer.length > MAX_IMAGE_BYTES) {
    throw new Error(`Emoji image generation too-large: image exceeds ${MAX_IMAGE_BYTES} bytes`);
  }

  return imageBuffer;
}

async function generateWithGoogleGenerateContent({
  productName,
  description,
  apiKey,
  model,
}: GenerateImageWithModelInput): Promise<GeneratedImage> {
  const prompt = getEmojiGenerationPrompt(productName, description);
  const ai = new GoogleGenAI({ apiKey });

  const response = await ai.models.generateContent({
    model,
    contents: prompt,
    config: {
      responseModalities: ['IMAGE'],
      imageConfig: { aspectRatio: '1:1' },
    },
  });

  return {
    imageBuffer: readGenerateContentImage(response),
    model,
    prompt,
  };
}

export async function generateWithGoogleImage(input: GenerateImageInput): Promise<GeneratedImage> {
  const configuredModel = readModelEnv(GOOGLE_IMAGE_MODEL_ENV);
  if (configuredModel === undefined) {
    return generateWithLegacyGemini(input);
  }

  // Configuration is validated before any client is created or any request is sent.
  const adapter = resolveGoogleImageAdapter(configuredModel);
  const modelInput = { ...input, model: configuredModel };

  if (adapter === 'generateImages') {
    return generateWithGoogleImages(modelInput);
  }
  return generateWithGoogleGenerateContent(modelInput);
}

export async function generateWithOpenAI({
  productName,
  description,
  apiKey,
}: GenerateImageInput): Promise<GeneratedImage> {
  const prompt = getEmojiGenerationPrompt(productName, description);
  const model = readModelEnv(OPENAI_IMAGE_MODEL_ENV) ?? DEFAULT_OPENAI_IMAGE_MODEL;
  const openai = new OpenAI({ apiKey });

  const result = await openai.images.generate({
    model,
    prompt,
  });

  const imageBase64 = result.data?.[0]?.b64_json;
  if (!imageBase64) {
    throw new Error('No image data from GPT Image');
  }

  return {
    imageBuffer: Buffer.from(imageBase64, 'base64'),
    model,
    prompt,
  };
}
